services:
  pg_chainlink:
    image: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - database.env
    volumes:
      - /Users/darbease/Demos/.chainlink-goerli/data:/var/lib/postgresql/data/
  chainlink:
    image: "smartcontract/chainlink:1.9.0"
    env_file:
      - .env
    depends_on:
      - pg_chainlink
    ports:
      - "6688:6688"
    volumes:
      - /Users/darbease/Demos/.chainlink-goerli/chainlink-volume:/chainlink/
    command: node start --password /chainlink/password.txt --api /chainlink/apicredentials.txt